name: CI Pipeline

on:
  push:
    branches:
      - main
      - celia
  pull_request:
    branches:
      - main
      - celia

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: frontend

  steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: npm 21.6.2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false
